# Fly.io configuration for QaAI Legal Assistant
app = "qaai-legal-assistant"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  API_HOST = "0.0.0.0"
  DATABASE_URL = "sqlite:///./data/qaai.db"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[[mounts]]
  source = "qaai_data"
  destination = "/app/data"

[deploy]
  release_command = "python -c 'import os; os.makedirs(\"data/files\", exist_ok=True); os.makedirs(\"data/index\", exist_ok=True)'"